# Nombre del servicio: https://genesys-api.onrender.com/

services:
  - name: genesys_api
    type: web
    runtime: docker
    repo: https://github.com/YordanoBOG/cc-practicas-24-25
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    autoDeploy: true
    envVars:
      - key: PAAS
        value: RENDER
      - key: PORT
        value: 8000
      - key: MONGO_DB
        fromService:
          type: pserv
          name: mongo-db
          property: connectionString

  - type: pserv
    name: mongo-db
    runtime: docker
    region: frankfurt
    plan: free
    autoDeploy: true
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10

  #- name: logger
    #runtime: docker
    #region: frankfurt
    #plan: free