# Nombre del servicio: https://genesys-api.onrender.com/

services:
  - name: genesys_api
    type: web
    runtime: docker
    repo: https://github.com/YordanoBOG/cc-practicas-24-25
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    autoDeploy: true
    envVars:
      - key: PAAS
        value: RENDER
      - key: PORT
        value: 8000
      - key: DATABASE_URI
        value: mongodb://mongo:27017/mydb
      - key: LOGGER
        value: logger:24224
    healthCheckPath: /health

  - name: logger
    type: pserv
    runtime: docker
    dockerfilePath: logger.Dockerfile
    region: frankfurt
    plan: free
    envVars: []

  - type: pserv
    runtime: docker
    name: mongo
    region: frankfurt
    dockerfilePath: mongo.Dockerfile
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: securepassword
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 10
