# Nombre del servicio: https://genesys-api.onrender.com/

services:
  - name: genesys_api
    type: web
    runtime: docker
    repo: https://github.com/YordanoBOG/cc-practicas-24-25
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    autoDeploy: true
    envVars:
      - key: PAAS
        value: RENDER
      - key: PORT
        value: 8000

  # start command: python3 app.py

  #- name: mongo_db
    #type: privateService
    #runtime: docker
    #region: frankfurt
    #plan: free
    #image: mongo:6.0
    #envVars:
      #MONGO_DB: mydb

  #- name: logger
    #runtime: docker
    #region: frankfurt
    #plan: free