# Nombre del servicio: https://genesys-api.onrender.com/

services:
  - name: genesys_api
    type: web
    runtime: docker
    repo: https://github.com/YordanoBOG/cc-practicas-24-25
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    autoDeploy: true
    envVars:
      - key: PAAS
        value: RENDER
      - key: PORT
        value: 8000
      - key: MONGO_DB
        fromService:
          type: pserv
          name: mongo-db
          property: connectionString
      #- key: MONGO_URI
        #value: mongodb://mongo:27017/mydb
      - key: LOGGER_HOST
        fromService:
          type: pserv
          name: logger
          property: connectionString

  - name: mongo-db
    type: pserv
    runtime: docker
    dockerfilePath: mongo.Dockerfile
    region: frankfurt
    plan: free
    envVars: []

  - name: logger
    type: pserv
    runtime: docker
    dockerfilePath: logger.Dockerfile
    region: frankfurt
    plan: free
    envVars: []

