# docker-compose.yml
version: '3.8'

services:
  api:
    build: ./api
    container_name: genesys_api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongo_db
      - "27017:27017"
    networks:
      - app_network

  logger:
    image: fluent/fluentd:latest
    container_name: logger
    ports:
      - "24224:24224"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge