name: Test and Publish Docker Containers

on:
  push:
    branches:
      - main

jobs:
  test-containers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker compose
      run: apt-get install docker-compose

    - name: Start containers with Docker Compose
      run: docker-compose up --build

    - name: Test API service
      run: |
        ./test_api_container.sh

    - name: Teardown containers
      run: docker-compose down --volumes

