name: Publish Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/api:latest
          ghcr.io/${{ github.repository_owner }}/api:${{ github.sha }}

    - name: Build and push Mongo image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./mongo.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/mongo:latest
          ghcr.io/${{ github.repository_owner }}/mongo:${{ github.sha }}

    - name: Build and push Logger image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./logger.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/logger:latest
          ghcr.io/${{ github.repository_owner }}/logger:${{ github.sha }}