name: Test and Publish Docker Containers

on:
  push:
    branches:
      - main

jobs:
  test-containers:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build API container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: api-test:latest

    - name: Build Mongo container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./mongo.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: mongo-test:latest

    - name: Build Logger container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./logger.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: logger-test:latest

    - name: Start containers with Docker Compose
      run: docker-compose up -d

    - name: Run tests on API service
      run: |
        sleep 20  # Wait for the service to start
        curl -X GET http://localhost:8000/health

    - name: Run tests on Mongo service
      run: |
        sleep 5  # Wait for Mongo to initialize
        docker exec -it mongo_db mongo --eval "db.runCommand({ ping: 1 })"

    - name: Run tests on Logger service
      run: |
        sleep 5  # Wait for Fluentd to initialize
        curl -X POST -d '{"message": "test"}' http://localhost:24224/test.tag

    - name: Teardown containers
      run: docker-compose down --volumes